# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "Aula_4" ]
  pull_request:
    branches: [ "Aula_4" ]

jobs:

  test:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    #- name: Build
      #run: go build -v main.go
      
    #- name: Test
      #run: go test -v main_test.go

    - name: Test Secret Key from Environment
      env:
       SECRET: ${{ secrets.teste }}
      run: echo env.SECRET

    - name: Test Secret Key directly
      run: echo ${{ secrets.teste }}
